# Generated by Django 5.2.5 on 2025-09-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_declarant_id', models.PositiveIntegerField(unique=True)),
                ('api_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('work_place', models.CharField(blank=True, max_length=255, null=True)),
                ('work_post', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('declarant', 'Декларант'), ('family', 'Член сім’ї'), ('person', 'Фізична особа (третя)'), ('company', 'Юридична особа/компанія'), ('state', 'Держава'), ('other', 'Інше')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('identifier', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField()),
                ('declaration_year', models.PositiveSmallIntegerField()),
                ('declaration_type', models.PositiveSmallIntegerField(choices=[(1, 'Щорічна'), (2, 'Перед звільненням'), (3, 'Після звільнення'), (4, 'Кандидата на посаду')])),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.declarant')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('sources', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarations', models.ManyToManyField(related_name='incomes', to='core.declaration')),
                ('owners', models.ManyToManyField(related_name='incomes', to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.UUIDField()),
                ('relation_type', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarations', models.ManyToManyField(related_name='family_members', to='core.declaration')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='core.owner')),
            ],
        ),
        migrations.AddField(
            model_name='declarant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declarant', to='core.owner'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarations', models.ManyToManyField(related_name='bank_accounts', to='core.declaration')),
                ('owners', models.ManyToManyField(related_name='bank_accounts', to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('other_object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_date_assessment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('owning_date', models.DateField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('object_cost_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(related_name='real_estates', to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.CharField(max_length=100)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.declaration')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realestate')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='declarations',
            field=models.ManyToManyField(related_name='real_estates', through='core.RealEstateDeclaration', to='core.declaration'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('owning_date', models.DateField(blank=True, null=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarations', models.ManyToManyField(related_name='vehicles', to='core.declaration')),
                ('owners', models.ManyToManyField(related_name='vehicles', to='core.owner')),
            ],
        ),
        migrations.AddConstraint(
            model_name='realestatedeclaration',
            constraint=models.UniqueConstraint(fields=('declaration', 'iteration', 'real_estate'), name='unique_real_estate_declarations_iteration'),
        ),
    ]
