# Generated by Django 5.2.5 on 2025-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='declarant',
            field=models.ManyToManyField(related_name='customer_users', to='core.declarant'),
        ),
    ]
