from django.db import models


class SubjectRelationType(models.TextChoices):
    HUSBAND = "чоловік", "чоловік"
    WIFE = "дружина", "дружина"
    FATHER = "батько", "батько"
    MOTHER = "мати", "мати"
    STEP_FATHER = "вітчим", "вітчим"
    STEPMOTHER = "мачуха", "мачуха"
    SON = "син", "син"
    DAUGHTER = "дочка", "дочка"
    STEPSON = "пасинок", "пасинок"
    STEPDAUGHTER = "падчерка", "падчерка"
    BROTHER = "рідний брат", "рідний брат"
    SISTER = "рідна сестра", "рідна сестра"
    GRANDFATHER = "дід", "дід"
    GRANDMOTHER = "баба", "баба"
    GREAT_GRANDFATHER = "прадід", "прадід"
    GREAT_GRANDMOTHER = "прабаба", "прабаба"
    GRANDSON = "внук", "внук"
    GRANDDAUGHTER = "внучка", "внучка"
    GREAT_GRANDSON = "правнук", "правнук"
    GREAT_GRANDDAUGHTER = "правнучка", "правнучка"
    SON_IN_LAW = "зять", "зять"
    DAUGHTER_IN_LAW = "невістка", "невістка"
    FATHER_IN_LAW = "тесть", "тесть"
    MOTHER_IN_LAW = "теща", "теща"
    FATHER_OF_HUSBAND = "свекор", "свекор"
    MOTHER_OF_HUSBAND = "свекруха", "свекруха"
    GUARDIAN = "опікун", "опікун"
    CUSTODIAN = "піклувальник", "піклувальник"
    UNDER_GUARDIANSHIP = "особа, яка перебуває під опікою", "особа, яка перебуває під опікою"
    UNDER_CUSTODY = "особа, яка перебуває під піклуванням", "особа, яка перебуває під піклуванням"
    COHABITANT = "особи, які спільно проживають та не перебувають у шлюбі", "особи, які спільно проживають та не перебувають у шлюбі"
    OTHER_RELATION = "інший зв'язок", "інший зв'язок"

class CitizenshipType(models.IntegerChoices):
    NO_CITIZENSHIP = 0, "Без громадянства"
    UKRAINE = 1, "Україна"
    AUSTRALIA = 2, "Австралія"
    AUSTRIA = 3, "Австрія"
    AZERBAIJAN = 4, "Азербайджан"
    ALAND_ISLANDS = 5, "Аландські острови"
    ALBANIA = 6, "Албанія"
    ALGERIA = 7, "Алжир"
    AMERICAN_SAMOA = 8, "Американське Самоа"
    AMERICAN_VIRGIN_ISLANDS = 9, "Американські Віргінські острови"
    ANGUILLA = 10, "Ангілья"
    ANGOLA = 11, "Ангола"
    ANDORRA = 12, "Андорра"
    ANTARCTICA = 13, "Антарктида"
    ANTIGUA_AND_BARBUDA = 14, "Антигуа і Барбуда"
    ARGENTINA = 15, "Аргентина"
    ARUBA = 16, "Аруба"
    AFGHANISTAN = 17, "Афганістан"
    BAHAMAS = 18, "Багамські Острови"
    BANGLADESH = 19, "Бангладеш"
    BARBADOS = 20, "Барбадос"
    BAHRAIN = 21, "Бахрейн"
    BELIZE = 22, "Беліз"
    BELGIUM = 23, "Бельгія"
    BENIN = 24, "Бенін"
    BERMUDA = 25, "Бермудські острови"
    BELARUS = 26, "Білорусь"
    BULGARIA = 27, "Болгарія"
    BOLIVIA = 28, "Болівія"
    BOSNIA_AND_HERZEGOVINA = 29, "Боснія і Герцеговина"
    BOTSWANA = 30, "Ботсвана"
    BRAZIL = 31, "Бразилія"
    BRITISH_INDIAN_OCEAN_TERRITORY = 32, "Британська територія в Індійському океані"
    BRITISH_VIRGIN_ISLANDS = 33, "Британські Віргінські острови"
    BRUNEI = 34, "Бруней"
    BURKINA_FASO = 35, "Буркіна-Фасо"
    BURUNDI = 36, "Бурунді"
    BHUTAN = 37, "Бутан"
    VANUATU = 38, "Вануату"
    VATICAN = 39, "Ватикан"
    UNITED_KINGDOM = 40, "Велика Британія"
    VENEZUELA = 41, "Венесуела"
    VIETNAM = 42, "В'єтнам"
    ARMENIA = 43, "Вірменія"
    WALLIS_AND_FUTUNA = 44, "Волліс і Футуна"
    GABON = 45, "Габон"
    HAITI = 46, "Гаїті"
    GUYANA = 47, "Гаяна"
    GAMBIA = 48, "Гамбія"
    GHANA = 49, "Гана"
    GUADELOUPE = 50, "Гваделупа"
    GUATEMALA = 51, "Гватемала"
    GUINEA = 52, "Гвінея"
    GUINEA_BISSAU = 53, "Гвінея-Бісау"
    GUERNSEY = 54, "Гернсі"
    HONDURAS = 55, "Гондурас"
    HONG_KONG = 56, "Гонконг"
    GRENADA = 57, "Гренада"
    GREECE = 58, "Греція"
    GEORGIA = 59, "Грузія"
    GUAM = 60, "Гуам"
    GIBRALTAR = 61, "Гібралтар"
    GREENLAND = 62, "Ґренландія"
    DENMARK = 63, "Данія"
    DRC = 64, "ДР Конго"
    JERSEY = 65, "Джерсі"
    DJIBOUTI = 66, "Джибуті"
    DOMINICA = 67, "Домініка"
    DOMINICAN_REPUBLIC = 68, "Домініканська Республіка"
    US_MINOR_OUTLYING_ISLANDS = 69, "Зовнішні малі острови США"
    ECUADOR = 70, "Еквадор"
    EQUATORIAL_GUINEA = 71, "Екваторіальна Гвінея"
    ERITREA = 72, "Еритрея"
    ESTONIA = 73, "Естонія"
    ETHIOPIA = 74, "Ефіопія"
    EGYPT = 75, "Єгипет"
    YEMEN = 76, "Ємен"
    ZAMBIA = 77, "Замбія"
    WESTERN_SAHARA = 78, "Західна Сахара"
    ZIMBABWE = 79, "Зімбабве"
    ISRAEL = 80, "Ізраїль"
    INDIA = 81, "Індія"
    INDONESIA = 82, "Індонезія"
    IRAQ = 83, "Ірак"
    IRAN = 84, "Іран"
    IRELAND = 85, "Ірландія"
    ICELAND = 86, "Ісландія"
    SPAIN = 87, "Іспанія"
    ITALY = 88, "Італія"
    JORDAN = 89, "Йорданія"
    CABO_VERDE = 90, "Кабо-Верде"
    KAZAKHSTAN = 91, "Казахстан"
    CAYMAN_ISLANDS = 92, "Кайманові острови"
    CAMBODIA = 93, "Камбоджа"
    CAMEROON = 94, "Камерун"
    CANADA = 95, "Канада"
    QATAR = 96, "Катар"
    KENYA = 97, "Кенія"
    KYRGYZSTAN = 98, "Киргизстан"
    CHINA = 99, "КНР"
    NORTH_KOREA = 100, "Північна Корея"
    CYPRUS = 101, "Кіпр"
    KIRIBATI = 102, "Кірибаті"
    COCOS_ISLANDS = 103, "Кокосові острови (Кілінг)"
    COLOMBIA = 104, "Колумбія"
    COMOROS = 105, "Коморські Острови"
    CONGO = 106, "Конго"
    COSTA_RICA = 107, "Коста-Рика"
    COTE_DIVOIRE = 108, "Кот-д'Івуар"
    CUBA = 109, "Куба"
    KUWAIT = 110, "Кувейт"
    LAOS = 111, "Лаос"
    LATVIA = 112, "Латвія"
    LESOTHO = 113, "Лесото"
    LITHUANIA = 114, "Литва"
    LIBERIA = 115, "Ліберія"
    LEBANON = 116, "Ліван"
    LIBYA = 117, "Лівія"
    LIECHTENSTEIN = 118, "Ліхтенштейн"
    LUXEMBOURG = 119, "Люксембург"
    MAURITIUS = 120, "Маврикій"
    MAURITANIA = 121, "Мавританія"
    MADAGASCAR = 122, "Мадагаскар"
    MAYOTTE = 123, "Майотта"
    MACAO = 124, "Макао"
    MACEDONIA = 125, "Македонія"
    MALAWI = 126, "Малаві"
    MALAYSIA = 127, "Малайзія"
    MALI = 128, "Малі"
    MALDIVES = 129, "Мальдіви"
    MALTA = 130, "Мальта"
    MOROCCO = 131, "Марокко"
    MARTINIQUE = 132, "Мартиніка"
    MARSHALL_ISLANDS = 133, "Маршаллові Острови"
    MEXICO = 134, "Мексика"
    MOZAMBIQUE = 135, "Мозамбік"
    MOLDOVA = 136, "Молдова"
    MONACO = 137, "Монако"
    MONGOLIA = 138, "Монголія"
    MONTSERRAT = 139, "Монтсеррат"
    MYANMAR = 140, "М'янма"
    NAMIBIA = 141, "Намібія"
    NAURU = 142, "Науру"
    NEPAL = 143, "Непал"
    NIGER = 144, "Нігер"
    NIGERIA = 145, "Нігерія"
    NETHERLANDS = 146, "Нідерланди"
    NETHERLANDS_ANTILLES = 147, "Нідерландські Антильські острови"
    NICARAGUA = 148, "Нікарагуа"
    GERMANY = 149, "Німеччина"
    NIUE = 150, "Ніуе"
    NEW_ZEALAND = 151, "Нова Зеландія"
    NEW_CALEDONIA = 152, "Нова Каледонія"
    NORWAY = 153, "Норвегія"
    UAE = 154, "ОАЕ"
    OMAN = 155, "Оман"
    BOUVET_ISLAND = 156, "Острів Буве"
    ISLE_OF_MAN = 157, "Острів Мен"
    NORFOLK_ISLAND = 158, "Острів Норфолк"
    CHRISTMAS_ISLAND = 159, "Острів Різдва"
    SAINT_HELENA_TRISTAN_DA_CUNHA = 160, "Острови Святої Єлени, Вознесіння і Тристан-да-Кунья"
    HEARD_MACDONALD_ISLANDS = 161, "Острови Герд і Макдональд"
    COOK_ISLANDS = 162, "Острови Кука"
    PAKISTAN = 163, "Пакистан"
    PALAU = 164, "Палау"
    PALESTINE = 165, "Палестина"
    PANAMA = 166, "Панама"
    PAPUA_NEW_GUINEA = 167, "Папуа - Нова Гвінея"
    PARAGUAY = 168, "Парагвай"
    PERU = 169, "Перу"
    SOUTH_GEORGIA_SANDWICH_ISLANDS = 170, "Південна Джорджія та Південні Сандвічеві острови"
    SOUTH_KOREA = 171, "Південна Корея"
    SOUTH_SUDAN = 172, "Південний Судан"
    SOUTH_AFRICA = 173, "ПАР"
    NORTHERN_MARIANA_ISLANDS = 174, "Північні Маріанські острови"
    PITCAIRN = 175, "Піткерн"
    POLAND = 176, "Польща"
    PORTUGAL = 177, "Португалія"
    PUERTO_RICO = 178, "Пуерто-Рико"
    REUNION = 179, "Реюньйон"
    RUSSIA = 180, "Росія"
    RWANDA = 181, "Руанда"
    ROMANIA = 182, "Румунія"
    EL_SALVADOR = 183, "Сальвадор"
    SAMOA = 184, "Самоа"
    SAN_MARINO = 185, "Сан-Марино"
    SAO_TOME_PRINCIPE = 186, "Сан-Томе і Принсіпі"
    SAUDI_ARABIA = 187, "Саудівська Аравія"
    ESWATINI = 188, "Свазіленд"
    SVALBARD_JAN_MAYEN = 189, "Свальбард і Ян-Маєн"
    SEYCHELLES = 190, "Сейшельські Острови"
    SAINT_BARTHELEMY = 191, "Сен-Бартельмі"
    SENEGAL = 192, "Сенегал"
    SAINT_MARTIN = 193, "Сен-Мартін"
    SAINT_PIERRE_MIQUELON = 194, "Сен-П'єр і Мікелон"
    SAINT_VINCENT_GRENADINES = 195, "Сент-Вінсент і Гренадини"
    SAINT_KITTS_NEVIS = 196, "Сент-Кіттс і Невіс"
    SAINT_LUCIA = 197, "Сент-Люсія"
    SERBIA = 198, "Сербія"
    SIERRA_LEONE = 209, "Сьєрра-Леоне"
    SYRIA = 199, "Сирія"
    SINGAPORE = 200, "Сінгапур"
    SLOVAKIA = 201, "Словаччина"
    SLOVENIA = 202, "Словенія"
    SOLOMON_ISLANDS = 203, "Соломонові Острови"
    SOMALIA = 204, "Сомалі"
    USA = 205, "США"
    SUDAN = 206, "Судан"
    SURINAME = 207, "Суринам"
    EAST_TIMOR = 208, "Східний Тимор"
    TAJIKISTAN = 210, "Таджикистан"
    THAILAND = 211, "Таїланд"
    TAIWAN = 212, "Тайвань"
    TANZANIA = 213, "Танзанія"
    TURKS_AND_CAICOS_ISLANDS = 214, "Острови Теркс і Кайкос"
    TOGO = 215, "Того"
    TOKELAU = 216, "Токелау"
    TONGA = 217, "Тонга"
    TRINIDAD_AND_TOBAGO = 218, "Тринідад і Тобаго"
    TUVALU = 219, "Тувалу"
    TUNISIA = 220, "Туніс"
    TURKEY = 221, "Туреччина"
    TURKMENISTAN = 222, "Туркменістан"
    UGANDA = 223, "Уганда"
    HUNGARY = 224, "Угорщина"
    UZBEKISTAN = 225, "Узбекистан"
    URUGUAY = 227, "Уругвай"
    FAROE_ISLANDS = 228, "Фарерські острови"
    FEDERATED_STATES_OF_MICRONESIA = 229, "Федеративні Штати Мікронезії"
    FIJI = 230, "Фіджі"
    PHILIPPINES = 231, "Філіппіни"
    FINLAND = 232, "Фінляндія"
    FALKLAND_ISLANDS = 233, "Фолклендські (Мальвінські) острови"
    FRANCE = 234, "Франція"
    FRENCH_GUIANA = 235, "Французька Гвіана"
    FRENCH_POLYNESIA = 236, "Французька Полінезія"
    FRENCH_SOUTHERN_TERRITORIES = 237, "Французькі Південні території"
    CROATIA = 238, "Хорватія"
    CENTRAL_AFRICAN_REPUBLIC = 239, "Центральноафриканська Республіка"
    CHAD = 240, "Чад"
    CZECH_REPUBLIC = 241, "Чехія"
    CHILE = 242, "Чилі"
    MONTENEGRO = 243, "Чорногорія"
    SWITZERLAND = 244, "Швейцарія"
    SWEDEN = 245, "Швеція"
    SRI_LANKA = 246, "Шрі-Ланка"
    JAMAICA = 247, "Ямайка"
    JAPAN = 248, "Японія"

class FamilyMember(models.Model):
    # Id
    api_id = models.UUIDField() # id члена сім'ї API НАЗК, наприклад: 1490088457731, 1490088585684
    # Звичайні поля
    subjectRelation = models.CharField(max_length=100, choices=SubjectRelationType.choices, null=True, blank=True)
    citizenship = models.PositiveSmallIntegerField( choices=CitizenshipType.choices, null=True, blank=True)
    surname = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=255) # область
    city = models.CharField(max_length=255) # населений пункт

    # Зв'язки
    declarations = models.ManyToManyField("Declaration", related_name='family_members')
    owner = models.OneToOneField("Owner", on_delete=models.CASCADE, related_name="family_member")
    # Метадані
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.subjectRelation and hasattr(self, 'get_subjectRelation_display'):
            relation = self.get_subjectRelation_display()
        else:
            relation = "Не вказано зв’язок"

        if self.citizenship is not None and hasattr(self, 'get_citizenship_display'):
            citizenship = self.get_citizenship_display()
        else:
            citizenship = "Невідоме громадянство"

        patronymic = f" {self.patronymic}" if self.patronymic else ""
        region = f", регіон: {self.region}" if self.region else ""
        city = f", місто: {self.city}" if self.city else ""

        return f"{relation}: {self.surname} {self.name}{patronymic} ({citizenship}){region}{city}"